In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_excel('Inventory Survey Data of Machinery_Matam_As of July 2025_Analysis_Boly.xlsx', sheet_name='Raw Data_modified', header=1)
df.head(10)

,N°,Dép,Nom de l'Entreprise,Privé/Union,Type materiel,Localité,Zone SAED,Chef de l'Entreprise,Contact,Marque,...,Unnamed: 18,Service Provider\n(Extract),Service Provider\n(List),Service Provider\n(Extract).1,Service Provider\n(List).1,Unnamed: 23,List of Service provider,Form,List of Service provider.1,Form.1
0,1.0,Kanel,Abdoulaye Bocar NDIAYE,Private,Tracteur,Wouro Sidy,Wouro Sidy,Abdoulaye Bocar NDIAYE,771654286,TAFE,...,NaN,NaN,NaN,NaN,NaN,NaN,Oumar Aguibou SOW,Union,Union Hydraulique de Hamady Ounaré,Union
1,2.0,Matam,Abdoulaye Djiby THIAM,Private,Tracteur,Nabadji Civol,Nabadji,Abdoulaye Djiby THIAM,776365447,TAFE,...,NaN,NaN,NaN,NaN,NaN,NaN,Union des GIE de Diamoungeul 1 et 2,Union,GIE Dagano,Private
2,3.0,Kanel,Abou DIAW,Private,Tracteur,Ounaré,Wouro Sidy,Abou DIAW,776143821,TAFE,...,NaN,NaN,NaN,NaN,NaN,NaN,DIENG et Fammile,Private,Union du Casier Doumga Ouro Thierno,Union
3,4.0,Matam,Comité de Gestion de Koundel 3,Private,Tracteur,Nabadji Civol,Nabadji,\nAbdoulaye Saidou Diaw,774077602,VALTRA,...,NaN,NaN,NaN,NaN,NaN,NaN,Harouna,Private,Makhana Diéri,Private
4,5.0,Kanel,Aboubacry Goby BASSOUM,Private,Tracteur,Kanel,Wouro Sidy,Aboubacry Goby BASSOUM,77 564 25 33,TAFE,...,NaN,NaN,NaN,NaN,NaN,NaN,Samba KANE,Private,Union Hydraulique de Kobilo,Union
5,6.0,Matam,Comité de Gestion de Woudourou 1,Private,Tracteur,Nabadji Civol,Nabadji,Seydou Kane,77 617 00 25\n77 555 77 98,VALTRA,...,NaN,NaN,NaN,NaN,NaN,NaN,Union Hydraulique de Dolol/Wodobéré,Union,Union Régionale des Interprofessionnels de Sem...,Private
6,7.0,Kanel,Association des Agriculteurs de Waoundé,Private,Tracteur,Waoundé,Orkadiere,Samba Camara,77 562 49 16,John Deere,...,NaN,NaN,NaN,NaN,NaN,NaN,Union Hydraulique de Hamady Ounaré,Union,GIE Townde,Private
7,8.0,Matam,Déworoy Jokkéré Endam,Private,Tracteur,Nabadji Civol,Nabadji,Arona Sall,78 496 44 02,John Deere,...,NaN,NaN,NaN,NaN,NaN,NaN,Abdoulaye KANE,Private,Union Hydraulique de Ndouloumadji,Union
8,9.0,Kanel,Bocar DAFF,Private,Tracteur,Ndendory,Ndendory,Bocar DAFF,775759153,TAFE,...,NaN,NaN,NaN,NaN,NaN,NaN,Diango DIABY,Private,NaN,NaN
9,10.0,Matam,Dieynaba Abdoul SY,Private,Tracteur,Agnam Civol,Agnam/Oréfondé,Dieynaba Abdoul SY,77120989,TAFE,...,NaN,NaN,NaN,NaN,NaN,NaN,GIE Alla Lewy,Private,NaN,NaN

In [10]:
df.describe()

,N°,Année acquisition,Année acquisition.1,Unnamed: 18,Service Provider\n(Extract),Service Provider\n(List),Service Provider\n(Extract).1,Service Provider\n(List).1,Unnamed: 23
count,109.000000,93.000000,74.000000,0.0,0.0,0.0,0.0,0.0,0.0
mean,55.000000,2016.376344,2015.932432,NaN,NaN,NaN,NaN,NaN,NaN
std,31.609598,2.988798,3.124499,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,2008.000000,2008.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,28.000000,2015.000000,2015.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,55.000000,2016.000000,2016.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,82.000000,2019.000000,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,109.000000,2020.000000,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.shape

(134, 28)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   N°                            109 non-null    float64
 1   Dép                           109 non-null    str
 2   Nom de l'Entreprise           109 non-null    str
 3   Privé/Union                   109 non-null    str
 4   Type materiel                 109 non-null    str
 5   Localité                      132 non-null    str
 6   Zone SAED                     132 non-null    object
 7   Chef de l'Entreprise          109 non-null    str
 8   Contact                       108 non-null    object
 9   Marque                        108 non-null    str
 10  Modèle                        107 non-null    object
 11  Numéro de série               19 non-null     str
 12  Etat                          104 non-null    str
 13  Année acquisition             93 non-null     float64
 14   Puissance                    101 non-null    object
 15  Offset/
Charrue               77 non-null     str
 16  Etat.1                        74 non-null     str
 17  Année acquisition.1           74 non-null     float64
 18  Unnamed: 18                   0 non-null      float64
 19  Service Provider
(Extract)    0 non-null      float64
 20  Service Provider
(List)       0 non-null      float64
 21  Service Provider
(Extract).1  0 non-null      float64
 22  Service Provider
(List).1     0 non-null      float64
 23  Unnamed: 23                   0 non-null      float64
 24  List of Service provider      75 non-null     str
 25  Form                          75 non-null     object
 26  List of Service provider.1    10 non-null     str
 27  Form.1                        10 non-null     object
dtypes: float64(9), object(6), str(13)
memory usage: 29.4+ KB

In [13]:
print(df.columns)

Index(['N°', 'Dép', 'Nom de l'Entreprise', 'Privé/Union', 'Type materiel',
       'Localité', 'Zone SAED', 'Chef de l'Entreprise', 'Contact', 'Marque',
       'Modèle', 'Numéro de série', 'Etat', 'Année acquisition', ' Puissance',
       'Offset/\nCharrue', 'Etat.1', 'Année acquisition.1', 'Unnamed: 18',
       'Service Provider\n(Extract)', 'Service Provider\n(List)',
       'Service Provider\n(Extract).1', 'Service Provider\n(List).1',
       'Unnamed: 23', 'List of Service provider', 'Form',
       'List of Service provider.1', 'Form.1'],
      dtype='str')

In [14]:
df1 = df.drop(columns=['Offset/\nCharrue', 'Etat.1', 'Année acquisition.1', 'Unnamed: 18',
       'Service Provider\n(Extract)', 'Service Provider\n(List)',
       'Service Provider\n(Extract).1', 'Service Provider\n(List).1',
       'Unnamed: 23', 'List of Service provider', 'Form',
       'List of Service provider.1', 'Form.1'])
print(df1.columns)

Index(['N°', 'Dép', 'Nom de l'Entreprise', 'Privé/Union', 'Type materiel',
       'Localité', 'Zone SAED', 'Chef de l'Entreprise', 'Contact', 'Marque',
       'Modèle', 'Numéro de série', 'Etat', 'Année acquisition', ' Puissance'],
      dtype='str')

In [15]:
df1.head()

,N°,Dép,Nom de l'Entreprise,Privé/Union,Type materiel,Localité,Zone SAED,Chef de l'Entreprise,Contact,Marque,Modèle,Numéro de série,Etat,Année acquisition,Puissance
0,1.0,Kanel,Abdoulaye Bocar NDIAYE,Private,Tracteur,Wouro Sidy,Wouro Sidy,Abdoulaye Bocar NDIAYE,771654286,TAFE,1002 4WD,NaN,Function,2019.0,100
1,2.0,Matam,Abdoulaye Djiby THIAM,Private,Tracteur,Nabadji Civol,Nabadji,Abdoulaye Djiby THIAM,776365447,TAFE,1002 4WD,NaN,Function,2019.0,100
2,3.0,Kanel,Abou DIAW,Private,Tracteur,Ounaré,Wouro Sidy,Abou DIAW,776143821,TAFE,1002 4WD,NaN,Function,2019.0,100
3,4.0,Matam,Comité de Gestion de Koundel 3,Private,Tracteur,Nabadji Civol,Nabadji,\nAbdoulaye Saidou Diaw,774077602,VALTRA,BH 165,NaN,Function,2015.0,Moins de 100
4,5.0,Kanel,Aboubacry Goby BASSOUM,Private,Tracteur,Kanel,Wouro Sidy,Aboubacry Goby BASSOUM,77 564 25 33,TAFE,1002 4WD,NaN,Function,2019.0,100

In [31]:
df1['Etat'].unique()

<StringArray>
['Function', 'Breakdown', nan]
Length: 3, dtype: str

In [22]:
df1["Type materiel"].unique()

<StringArray>
['Tracteur', 'Moissonneuse Batteuse ', nan]
Length: 3, dtype: str

In [16]:
df1.shape

(134, 15)

In [21]:
df_Inv_Agri = pd.read_excel('./data/Inventory of Agricutural Machinery_Senegal River Valley_210429.xlsx', sheet_name='Inventory', header=1, index_col=False)
df_Inv_Agri.head()

/workspaces/D-veloppement_mod-le_ML_suivi_MA_VFS/.venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Unnamed: 0,Dép,Nom de l'Entreprise,Privé/Union,Commune,Chef de l'Entreprise,Contact,Tracteur\nMarque,Tracteur Puissance,Tracteur \nEtat,...,Moissonneuse \nBatteuse\nMarque,MB Puissance,MB Etat,Année acquisition.2,Batteuse Marque,Batteuse Etat,Année acquisition.3,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,NaN,Dagana,Abdoul Fatah Diop,Individuel,Ronkh,Abdoul Fatah Diop,77 643 02 16,Aucune machine,NaN,NaN,...,Aucune machine,NaN,NaN,NaN,ASI,Bon,2016,NaN,NaN,NaN
1,NaN,Dagana,Abdoulaye Mbodj,Individuel,Ronkh,Abdoulaye Mbodj,77 553 85 10,John Deere,125,Bon,...,Aucune machine,NaN,NaN,NaN,Aucune machine,NaN,NaN,NaN,NaN,NaN
2,NaN,Dagana,Abdourahmane Diao,Privé,Dagana,Abdourahmane Diao,776059666,TAFE,100,Bon,...,Aucune machine,NaN,NaN,NaN,Aucune machine,NaN,NaN,NaN,NaN,NaN
3,NaN,Dagana,Aboubacry Deme,Privé,Richard Toll,Aboubacry Deme,77 442 43 74,John Deere,170,Bon,...,Aucune machine,NaN,NaN,NaN,Aucune machine,NaN,NaN,NaN,NaN,NaN
4,NaN,Dagana,ABY Gueye DT\n(A confirmer),NaN,NaN,NaN,NaN,Aucune machine,NaN,NaN,...,Aucune machine,NaN,NaN,NaN,ASI,Bon,2015,NaN,NaN,NaN

In [24]:
df_Inv_Agri.columns

Index(['Unnamed: 0', 'Dép', 'Nom de l'Entreprise', 'Privé/Union', 'Commune',
       'Chef de l'Entreprise', 'Contact', 'Tracteur\nMarque',
       'Tracteur Puissance', 'Tracteur \nEtat', 'Année acquisition',
       'Offset/\nCharrue', 'Offset/\nCharrue\nEtat', 'Année acquisition.1',
       'Moissonneuse \nBatteuse\nMarque', 'MB Puissance', 'MB Etat',
       'Année acquisition.2', 'Batteuse Marque', 'Batteuse Etat',
       'Année acquisition.3', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23'],
      dtype='str')

In [25]:
df_tracteur = df_Inv_Agri[['Tracteur\nMarque',
       'Tracteur Puissance', 'Tracteur \nEtat', 'Année acquisition']]
df_tracteur.head()

  Tracteur\nMarque Tracteur Puissance Tracteur \nEtat Année acquisition
0   Aucune machine                NaN             NaN               NaN
1       John Deere                125             Bon              2018
2             TAFE                100             Bon               NaN
3       John Deere                170             Bon              2014
4   Aucune machine                NaN             NaN               NaN

In [26]:
df_Moissonneuse = df_Inv_Agri[['Moissonneuse \nBatteuse\nMarque', 'MB Puissance', 'MB Etat',
       'Année acquisition.2']]
df_Moissonneuse.head()

  Moissonneuse \nBatteuse\nMarque MB Puissance MB Etat Année acquisition.2
0                  Aucune machine          NaN     NaN                 NaN
1                  Aucune machine          NaN     NaN                 NaN
2                  Aucune machine          NaN     NaN                 NaN
3                  Aucune machine          NaN     NaN                 NaN
4                  Aucune machine          NaN     NaN                 NaN

In [27]:
df_Moissonneuse['Moissonneuse \nBatteuse\nMarque'].unique()

array(['Aucune machine', 'World', 'VALTRA', 'MITSUBISHI', 'ISEKI',
       'New Holland', nan, 'Massey Ferguson', 'John Deere', 'CLAAS',
       'Field King', 'Sakpattana', 'Autre', 'Preet', 'CASE', 'Keizer',
       'ZOOMLION', 224], dtype=object)

In [28]:
df_Moissonneuse['MB Puissance'].unique()

array([nan, 'Moins de 100', 240, 130, 170, 250, 125, 180, 'Autre', 260,
       190, 220, 210, 140, 160, 135, 230, 110, 150, 145, 200],
      dtype=object)

In [29]:
df_Moissonneuse['MB Etat'].unique()

<StringArray>
[nan, 'Bon', 'En réparation', 'En panne', 'Mauvais', 'Abandonné']
Length: 6, dtype: str

In [30]:
df_Moissonneuse['Année acquisition.2'].unique()

array([nan, 2020, 2019, 2016, 2017, 2015, 2018, 2008, 2014, 2007, 2012,
       2013, 2010, 'Avant de 2005', 2006], dtype=object)